version: '3'
services:
  jenkins:
    build: 
      context: .
      dockerfile: jenkins_dockerfile
    user: root
    privileged: true # This might get me past Docker: permission denied
    ports:
      - "8080:8080"
      - "8082:8082" # For spring-petclinic app
      - "8084:8084" # For OWASP-ZAP exposure
    networks:
      - dev-network
    # command: sh -c "sudo service docker start && /usr/bin/tini -- /usr/local/bin/jenkins.sh "
    entrypoint: ["/bin/sh", "-c" , "sudo service docker start && /usr/bin/tini -- /usr/local/bin/jenkins.sh "]

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - dev-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - dev-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
    networks:
      - dev-network
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  owaspzap:
    image : zaproxy/zap-stable
    #image: securecodebox/zap
    ports:
      - "8081:8080"
    networks:
      - dev-network
    volumes:
      - proj-vol:/zap/wrk:rw
    command: "zap-baseline.py -t https://www.example.com -r report_html"

networks:
  dev-network:
    external: true

volumes:
  proj-vol:
    external: true
