version: '3'
services:
  jenkins:
    build: 
      context: .
      dockerfile: jenkins_dockerfile
    user: root
    privileged: true # This might get me past Docker: permission denied
    ports:
      - "8080:8080"
      - "8082:8082" # For spring-petclinic app
      - "8084:8084" # For OWASP-ZAP exposure
    networks:
      - dev-network
    # volumes:
    # - /var/run/docker.sock:/var/run/docker.sock # If this is unspecified, returns "Docker: not found" if it is, I get "docker: permission denied." 
    # - /usr/bin/docker:/usr/bin/docker # If this is unspecified, I get docker: not found

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - dev-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - dev-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
    networks:
      - dev-network
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  dev-network:
    external: true

volumes:
  proj-vol:
    external: true