global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jenkins'
    static_configs:
      - targets: ['192.168.1.2:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.1.4:9090']
