---
- name: Deploy Spring PetClinic Application
  hosts: new_ec2
  become: yes
  vars:
    jar_file: "/home/ubuntu/spring-petclinic-3.3.0-SNAPSHOT.jar"
  tasks:
    - name: Update the package list
      apt:
        update_cache: yes

    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Copy the Spring PetClinic JAR file to the EC2 instance
      copy:
        src: "{{ jar_file }}"
        dest: /home/ubuntu/spring-petclinic-3.3.0-SNAPSHOT.jar
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    - name: Check if the Spring PetClinic application is running
      shell: "pgrep -f spring-petclinic-3.3.0-SNAPSHOT.jar"
      register: pgrep_result
      ignore_errors: yes

    - name: Kill the Spring PetClinic application if it is running
      shell: "pkill -f spring-petclinic-3.3.0-SNAPSHOT.jar || true"
      when: pgrep_result.rc == 0
      ignore_errors: yes

    - name: Run the Spring PetClinic application
      shell: "nohup java -jar /home/ubuntu/spring-petclinic-3.3.0-SNAPSHOT.jar > /home/ubuntu/petclinic.log 2>&1 &"
      args:
        chdir: /home/ubuntu
      register: run_result

    - name: Debug - Check if the application is running
      shell: "ps aux | grep spring-petclinic-3.3.0-SNAPSHOT.jar"
      register: ps_result

    - debug:
        msg: "Run Result: {{ run_result }}"

    - debug:
        msg: "Process Status: {{ ps_result }}"
